# Generated by Django 2.0.6 on 2018-06-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storebranch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='product_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ProductPicture'),
        ),
    ]
